<a href="https://colab.research.google.com/github/trnayak11/Tensor/blob/main/00_tenserflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Tensor flow fundamental
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
#create tensor with tf.constant
scalar = tf.constant(8)
scalar
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,8],[10,8]])
matrix
matrix.ndim

2

In [ ]:
matrix = tf.constant([[10,8,5],[10,8,6],[10,8,7]])
matrix
matrix.ndim

2

In [ ]:
matrix_1 = tf.constant([[10,8,5],[10,8,6],[10,8,7]],dtype=tf.float16)
#matrix_1
matrix_1.ndim

2

In [ ]:
tensor = tf.constant([[[10,8,5]],[[10,8,6]],[[10,8,7]]],dtype=tf.float16)
#matrix_1
tensor.ndim

3

In [ ]:
#Tensor variable
change_var = tf.Variable([10,5])
unchange_var = tf.constant([15,7])
print(change_var[0])
#change_var[0]
change_var[0].assign(19)
print(change_var[0])
#unchange_var[0].assign(19)
change_var
print(type(change_var))

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(19, shape=(), dtype=int32)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [143]:
#creating random tensor
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2,3))
#random_1, random_2, random_1 == random_2
random_1


<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]],

       [[ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993]],

       [[-0.3522796 ,  0.40621263],
        [-1.0523509 ,  1.2054597 ],
        [ 1.6874489 , -0.4462975 ]]], dtype=float32)>

In [103]:
#Sufle a tensor
tf.random.set_seed(42)
not_shuffled = tf.constant([[11,8],[87,63],[98,8]])
#not_shuffled+
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[87, 63],
       [98,  8],
       [11,  8]], dtype=int32)>

In [106]:
import random
random.seed(6)
for i in range(5):
  print(random.randint(0,100),end=' ')
print('\n')
random.seed(6)
for i in range(5):
  print(random.randint(0,100),end=' ')

73 10 62 97 33 

73 10 62 97 33 

In [107]:
#Create tensor using numpy ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [177]:
import numpy as np
numpy_a = np.arange(1, 25, dtype=np.int32)
numpy_a
a = tf.constant(numpy_a, shape=(2,3,4)) #shape is important to notice.
a
#a.ndim

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>