<a href="https://colab.research.google.com/github/trnayak11/Tensor/blob/main/00Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
from numpy import *
import matplotlib.pyplot as  plt

print(torch.__version__)

2.5.1+cu121


In [ ]:
print("hello")

hello


In [ ]:
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [ ]:
vector = torch.tensor([2,5])
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([2,3])
matrix.shape
matrix.ndim

1

In [ ]:
#matrix
matrix = torch.tensor([[2,3],[4,7],[4,7]])
matrix.shape
matrix.ndim

2

In [ ]:
#matrix
matrix = torch.tensor([[[2,3]],[[4,7]],[[4,7]]])
matrix.shape
#matrix.ndim

torch.Size([3, 1, 2])

In [ ]:
random_tensor = torch.rand(size=(1,2,3,2))
random_tensor

tensor([[[[0.6071, 0.8355],
          [0.5089, 0.6003],
          [0.2713, 0.0690]],

         [[0.1177, 0.4428],
          [0.5863, 0.7521],
          [0.9221, 0.0099]]]])

In [ ]:
random_tensor = torch.rand(1,2,3,2)
random_tensor

tensor([[[[0.4026, 0.8984],
          [0.8412, 0.1466],
          [0.8691, 0.5935]],

         [[0.1593, 0.9647],
          [0.7986, 0.5546],
          [0.5604, 0.2760]]]])

In [ ]:
zeros = torch.zeros(2,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#range of tensor
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch_arang = torch.arange(start=1, end=1011, step=100)
torch_arang

tensor([   1,  101,  201,  301,  401,  501,  601,  701,  801,  901, 1001])

In [ ]:
ten_zeros = torch.ones_like(input = torch_arang)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
tensor_float = torch.tensor([3.2,2.5,8.6],dtype=None)
tensor_float.dtype

torch.float32

In [ ]:
tensor_float_32 = torch.tensor([3.2,2.5,8.6],dtype=torch.int32,device=None,requires_grad=False)
tensor_float_32
#tensor_float.dtype

tensor([3, 2, 8], dtype=torch.int32)

In [ ]:
tensor_float_16 = torch.tensor([3.2,2.5,8.6],dtype=torch.int16,device=None,requires_grad=False)
tensor_float_16

tensor([3, 2, 8], dtype=torch.int16)

In [ ]:
tensor_float_32 * tensor_float_16

tensor([ 9,  4, 64], dtype=torch.int32)

In [ ]:
some_tensor = torch.rand(size=(3,4))
some_tensor.dtype
print(some_tensor)
print(f"Datatype = {some_tensor.dtype}")
print(f"size = {some_tensor.size()} {some_tensor.shape}")
print(f"Device = {some_tensor.device}")

tensor([[0.3297, 0.7491, 0.7384, 0.0809],
        [0.7128, 0.0512, 0.2419, 0.6647],
        [0.4680, 0.7455, 0.6569, 0.4376]])
Datatype = torch.float32
size = torch.Size([3, 4]) torch.Size([3, 4])
Device = cpu


In [ ]:
#manipulating Tensors

In [ ]:
#ADITION
#SUBTRACTION
#MULTIPLICATION
#DIVISION
#MATRIX MULTIPLICATION

In [ ]:
#ADITION
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor1 + tensor2

tensor([2, 4, 6])

In [ ]:
#MULTIPLICATION
tensor1 = torch.tensor([1,2,3])
tensor1 * 10


tensor([20, 40, 60])

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor1 * tensor2

tensor([1, 4, 9])

In [ ]:
tensor1 = torch.tensor([[1,2,3],[1,2,3]])
tensor2 = torch.tensor([[9,6,5]])
tensor1 * tensor2

tensor([[ 9, 12, 15],
        [ 9, 12, 15]])

In [ ]:
# sameway it works for all operation. The above multiplication is element matriplication. The other way is to go for a matrix multiplication

In [ ]:
tensor1 = torch.tensor([[1,2,3],[1,2,3]])
tensor2 = torch.tensor([[9,6,5],[1,2,3]])
tensor1 * tensor2

tensor([[ 9, 12, 15],
        [ 1,  4,  9]])

In [ ]:
mat_1 = torch.tensor([1,2,3])
mat_2 = torch.tensor([1,2,3])
torch.matmul(mat_1,mat_2)
mat_1.ndim

1

In [ ]:
#matrix multiplication rule:-
# the inner dimension must match
# resulting matrix is same in shape of outer dimension

tensor_1 = torch.rand(size=(3,2))
print(tensor_1)
tensor_2 = torch.rand(size=(3,2))
print(tensor_2)
torch.matmul(tensor_1,tensor_2) # can not be done as inner dimension is not matching. shape (3,2), (3,2).. Here first element is outer dimension and second element is inner dimension



tensor([[0.3546, 0.5221],
        [0.0356, 0.6711],
        [0.7552, 0.6182]])
tensor([[0.0849, 0.8604],
        [0.1636, 0.9830],
        [0.7962, 0.4685]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_1 = torch.rand(size=(3,2))
print(tensor_1)
tensor_2 = torch.rand(size=(2,2))
print(tensor_2)
torch.matmul(tensor_1,tensor_2)   # this will work as inner dimension will match

tensor([[0.8013, 0.8272],
        [0.1584, 0.0910],
        [0.9929, 0.5465]])
tensor([[0.7043, 0.7228],
        [0.2985, 0.5922]])


tensor([[0.8112, 1.0690],
        [0.1387, 0.1684],
        [0.8624, 1.0413]])

In [ ]:
# Test
mat_t = [1,2,3]
mat_b = [1,2,3]
#print(mat_b)
result = 0
for i in range(len(mat_t)):
  #print(mat_t[i])
  result += mat_t[i] * mat_t[i]
print(result)


14


In [ ]:
mat_t = [[1,2,3]]
mat_b = [[1],[2],[3]]

for i in mat_t:
  for j in range(len(i)):
    print(i[j])
    for k in (range(len(mat_b))):
      print(mat_b[k])
    print(i[j], '+' ,mat_b[j])

1
[1]
[2]
[3]
1 + [1]
2
[1]
[2]
[3]
2 + [2]
3
[1]
[2]
[3]
3 + [3]


In [ ]:
mat_m = torch.tensor([[12,7,3],[4 ,5,6],[7 ,8,9]])
mat_n = torch.tensor([[5,8,1,2],[6,7,3,0],[4,5,9,1]])
torch.matmul(mat_m,mat_n)


tensor([[114, 160,  60,  27],
        [ 74,  97,  73,  14],
        [119, 157, 112,  23]])