<a href="https://colab.research.google.com/github/trnayak11/Tensor/blob/main/00Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
from numpy import *
import matplotlib.pyplot as  plt

print(torch.__version__)

2.5.1+cu121


In [ ]:
print("hello")

hello


In [ ]:
scalar = torch.tensor(7)
scalar
#scalar.ndim

tensor(7)

In [ ]:
vector = torch.tensor([2,5])
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([2,3])
matrix.shape
matrix.ndim

1

In [ ]:
#matrix
matrix = torch.tensor([[2,3],[4,7],[4,7]])
matrix.shape
matrix.ndim

2

In [ ]:
#matrix
matrix = torch.tensor([[[2,3]],[[4,7]],[[4,7]]])
matrix.shape
#matrix.ndim

torch.Size([3, 1, 2])

In [ ]:
random_tensor = torch.rand(size=(1,2,3,2))
random_tensor

tensor([[[[0.9690, 0.6794],
          [0.9263, 0.1241],
          [0.9369, 0.8702]],

         [[0.0496, 0.4489],
          [0.7675, 0.0997],
          [0.3117, 0.9703]]]])

In [ ]:
random_tensor = torch.rand(1,2,3,2)
random_tensor

tensor([[[[0.6106, 0.2474],
          [0.6378, 0.2914],
          [0.8379, 0.7033]],

         [[0.4898, 0.5482],
          [0.9909, 0.5077],
          [0.2713, 0.9743]]]])

In [ ]:
zeros = torch.zeros(2,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#range of tensor
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch_arang = torch.arange(start=1, end=1011, step=100)
torch_arang

tensor([   1,  101,  201,  301,  401,  501,  601,  701,  801,  901, 1001])

In [ ]:
ten_zeros = torch.ones_like(input = torch_arang)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
tensor_float = torch.tensor([3.2,2.5,8.6],dtype=None)
tensor_float.dtype

torch.float32

In [ ]:
tensor_float_32 = torch.tensor([3.2,2.5,8.6],dtype=torch.int32,device=None,requires_grad=False)
tensor_float_32
#tensor_float.dtype

tensor([3, 2, 8], dtype=torch.int32)

In [ ]:
tensor_float_16 = torch.tensor([3.2,2.5,8.6],dtype=torch.int16,device=None,requires_grad=False)
tensor_float_16

tensor([3, 2, 8], dtype=torch.int16)

In [ ]:
tensor_float_32 * tensor_float_16

tensor([ 9,  4, 64], dtype=torch.int32)

In [ ]:
some_tensor = torch.rand(size=(3,4))
some_tensor.dtype
print(some_tensor)
print(f"Datatype = {some_tensor.dtype}")
print(f"size = {some_tensor.size()} {some_tensor.shape}")
print(f"Device = {some_tensor.device}")

tensor([[0.8073, 0.9717, 0.9179, 0.4475],
        [0.8538, 0.9008, 0.2855, 0.9407],
        [0.3302, 0.3263, 0.9939, 0.2881]])
Datatype = torch.float32
size = torch.Size([3, 4]) torch.Size([3, 4])
Device = cpu


In [ ]:
#manipulating Tensors

In [ ]:
#ADITION
#SUBTRACTION
#MULTIPLICATION
#DIVISION
#MATRIX MULTIPLICATION

In [ ]:
#ADITION
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor1 + tensor2

tensor([2, 4, 6])

In [ ]:
#MULTIPLICATION
tensor1 = torch.tensor([1,2,3])
tensor1 * 10


tensor([10, 20, 30])

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor1 * tensor2

tensor([1, 4, 9])

In [ ]:
tensor1 = torch.tensor([[1,2,3],[1,2,3]])
tensor2 = torch.tensor([[9,6,5]])
tensor1 * tensor2

tensor([[ 9, 12, 15],
        [ 9, 12, 15]])

In [ ]:
# sameway it works for all operation. The above multiplication is element matriplication. The other way is to go for a matrix multiplication

In [ ]:
tensor1 = torch.tensor([[1,2,3],[1,2,3]])
tensor2 = torch.tensor([[9,6,5],[1,2,3]])
tensor1 * tensor2

tensor([[ 9, 12, 15],
        [ 1,  4,  9]])

In [ ]:
mat_1 = torch.tensor([1,2,3])
mat_2 = torch.tensor([1,2,3])
torch.matmul(mat_1,mat_2)
mat_1.ndim

1

In [ ]:
#matrix multiplication rule:-
# the inner dimension must match
# resulting matrix is same in shape of outer dimension

tensor_1 = torch.rand(size=(3,2))
print(tensor_1)
tensor_2 = torch.rand(size=(3,2))
print(tensor_2)
torch.matmul(tensor_1,tensor_2) # can not be done as inner dimension is not matching. shape (3,2), (3,2).. Here first element is outer dimension and second element is inner dimension



tensor([[0.6161, 0.6495],
        [0.2192, 0.2887],
        [0.9241, 0.8551]])
tensor([[0.7597, 0.1949],
        [0.4801, 0.7897],
        [0.3754, 0.5286]])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_1 = torch.rand(size=(3,2))
print(tensor_1)
tensor_2 = torch.rand(size=(2,2))
print(tensor_2)
torch.matmul(tensor_1,tensor_2)   # this will work as inner dimension will match

tensor([[0.2460, 0.9801],
        [0.0193, 0.7488],
        [0.8207, 0.2213]])
tensor([[0.2263, 0.8511],
        [0.2593, 0.0889]])


tensor([[0.3098, 0.2965],
        [0.1985, 0.0830],
        [0.2431, 0.7181]])

In [ ]:
# Test
mat_t = [1,2,3]
mat_b = [1,2,3]
#print(mat_b)
result = 0
for i in range(len(mat_t)):
  #print(mat_t[i])
  result += mat_t[i] * mat_t[i]
print(result)


14


In [ ]:
mat_t = [[1,2,3]]
mat_b = [[1],[2],[3]]

for i in mat_t:
  for j in range(len(i)):
    print(i[j])
    for k in (range(len(mat_b))):
      print(mat_b[k])
    print(i[j], '+' ,mat_b[j])

1
[1]
[2]
[3]
1 + [1]
2
[1]
[2]
[3]
2 + [2]
3
[1]
[2]
[3]
3 + [3]


In [ ]:
mat_m = torch.tensor([[12,7,3],[4 ,5,6],[7 ,8,9]])
mat_n = torch.tensor([[5,8,1,2],[6,7,3,0],[4,5,9,1]])
torch.matmul(mat_m,mat_n)


tensor([[114, 160,  60,  27],
        [ 74,  97,  73,  14],
        [119, 157, 112,  23]])

In [ ]:
mat_test = torch.tensor([[1,2],[3,4],[5,6]])
mat_test.T

NameError: name 'torch' is not defined

In [ ]:
#agregation, positional min max
x = torch.arange(0,100,10)
x
x.min()
x.max()
#x.mean()
torch.max(x)
x.type(torch.float32).mean()
torch.mean(x.type(torch.float32))
x.argmin()
x.argmax()

tensor(9)

In [26]:
#reshapping sqizin stacking
"""
reshapng:- reshape a input tensor to a defined shape
view:-return a view of an input tensor of certain shape but keep the saame memory as original tensor
stacking:- combine multiple tensor on top of each other(vstack) or side bt side(hstack)
sqeeze:- removes all 1 dimensios from a tensor
unsqeeze:- add one 1 dimension to a target tensor
permute:- return a view of the input with dimension permuted(swapped) in a certain way

"""
import torch
x= torch.arange(1.,10.)

x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [25]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))